import React, { useState, useEffect } from "react";

import Head from "next/head";
import Bluebar from "../../components/bluebar";
import NavigBar from "../../components/navigbar";
import ElementTitle from "../../components/elementtitle";
import YearLine from "../../components/yearline";
import ElementTimeline from "../../components/elementtimeline";
import Positioning from "../../components/positioning";
import ElementPatterns from "../../components/elementpatterns";
import CodeIdentifiers from "../../components/codeidentifiers";
import elements, { bing } from "../../data/elements"; // elements - google elements, bing - bing elements

import * as Parser from "ua-parser-js";

export async function getStaticProps(context) {
  const elname = context.params.elname;
  var element_google = Object.entries(elements).find((object) => {
    return object[0] == elname && object[1].engine == "G";
  });
  var element_bing = Object.entries(bing).find((object) => {
    return object[0] == elname && object[1].engine == "B";
  });
  return {
    props: {
      element_google: element_google ? element_google[1] : null,
      element_bing: element_bing ? element_bing[1] : null,
    }, // will be passed to the page component as props
  };
}

export async function getStaticPaths() {
  const paths = Object.entries(elements)
    .filter((elm) => elm[0] !== "null")
    .map((elm) => {
      return { params: { elname: elm[0] } };
    });

  Object.entries(bing).map((elm) => {
    paths.push({ params: { elname: elm[0] } });
  });

  return {
    paths,
    fallback: false, // return 404 when inexistent
  };
}

export default function ElementPage({ element_google, element_bing }) {
  const [element, setElement] = useState(
    element_google ? element_google : element_bing
  );
  const [engine, setEngine] = useState(element_google ? "G" : "B");
  useEffect(() => {
    engine == "G" ? setElement(element_google) : setElement(element_bing);
  }, [engine]);

  const changeEngine = () => {
    engine == "G" ? setEngine("B") : setEngine("G");
  };

  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar pagename="Elements" />
      <div className="container mt-3 mb-3 desktop-element">
        <div className="d-flex flex-column align-items-center">
          <ElementTitle title={element.name} type={element.type} />
        </div>

        <div className="row">
          <div className="col-6">
            <div className="d-flex flex-column align-items-center">
              <div className="element-engine">
                <img src={"../assets/google.png"} />
              </div>
            </div>
          </div>
          <div className="col-6">
            <div className="d-flex flex-column align-items-center">
              <div className="element-engine">
                <img src={"../assets/bing.png"} />
              </div>
            </div>
          </div>
        </div>
        <div className="sectiontitle">Visual Evolution</div>
        <div className="row">
          <div className="col-6">
            {element_google ? (
              <ElementTimeline serpelement={element_google} />
            ) : (
              "This element is exclusive to Bing"
            )}
          </div>
          <div className="col-6">
            {element_bing ? (
              <ElementTimeline serpelement={element_bing} />
            ) : (
              "This element is exclusive to Google"
            )}
          </div>
        </div>

        <div className="sectiontitle">Positioning</div>
        <div className="row">
          <div className="col-6">
            {element_google ? (
              <Positioning
                shortname={element_google.shortname}
                engine={element_google.engine}
                available={element_google.positioning}
              />
            ) : (
              ""
            )}
          </div>
          <div className="col-6">
            {element_bing ? (
              <Positioning
                shortname={element_bing.shortname}
                engine={element_bing.engine}
                available={element_bing.positioning}
              />
            ) : (
              ""
            )}
          </div>
        </div>

        <div className="sectiontitle">Presence timeline</div>
        <div className="row">
          <div className="col-6">
            {element_google ? (
              <YearLine present={element_google.presence} />
            ) : (
              ""
            )}
          </div>
          <div className="col-6">
            {element_bing ? <YearLine present={element_bing.presence} /> : ""}
          </div>
        </div>

        <div className="sectiontitle">HTML Identifiers</div>
        <div className="row">
          <div className="col-6 pr-2">
            {element_google ? (
              <CodeIdentifiers identifiers={element_google.identifiers} />
            ) : (
              ""
            )}
          </div>
          <div className="col-6 pl-2">
            {element_bing ? (
              <CodeIdentifiers identifiers={element_bing.identifiers} />
            ) : (
              ""
            )}
          </div>
        </div>

        <div className="sectiontitle">Design Patterns</div>
        <div className="row">
          <div className="col-6">
            {element_google ? (
              <ElementPatterns elm_patterns={element_google.patterns} />
            ) : (
              ""
            )}
          </div>
          <div className="col-6">
            {element_bing ? (
              <ElementPatterns elm_patterns={element_bing.patterns} />
            ) : (
              ""
            )}
          </div>
        </div>
      </div>
      <div className="container mt-3 mb-3 mobile-element">
        <div className="d-flex flex-column align-items-center">
          <div className="element-engine">
            <img
              src={"../assets/" + (engine == "G" ? "google" : "bing") + ".png"}
            />
          </div>
          <ElementTitle title={element.name} type={element.type} />
          <button
            onClick={changeEngine}
            type="button"
            className="btn btn-light mb-2"
            disabled={element_google && element_bing ? false : true}
          >
            {element_google && element_bing
              ? "Change engine"
              : "Exclusive element"}
          </button>
        </div>
        <div className="sectiontitle">Presence timeline</div>
        <YearLine present={element.presence} />

        <div className="row mt-4">
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Evolution</div>
            <ElementTimeline serpelement={element} />
          </div>
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Positioning</div>
            <Positioning
              shortname={element.shortname}
              engine={element.engine}
              available={element.positioning}
            />
            <div className="sectiontitle mt-4">HTML Identifiers</div>
            <CodeIdentifiers identifiers={element.identifiers} />
            <div className="sectiontitle mt-4">Design Patterns</div>
            <ElementPatterns elm_patterns={element.patterns} />
          </div>
        </div>
      </div>
    </div>
  );
}
