import Head from "next/head";
import Bluebar from "../../components/bluebar";
import NavigBar from "../../components/navigbar";
import ModuleTabs from "../../components/moduletabs";
import ElementTitle from "../../components/elementtitle";
import YearLine from "../../components/yearline";
import Timeline from "../../components/timeline";
import Positioning from "../../components/positioning";
import ElementPatterns from "../../components/elementpatterns";

export default function ElementPage() {
  const element = {
    name: "Local Pack",
    shortname: "localpack",
    type: "feature",
    engine: "G",
    presence: [2000, 2001, 2002, 2003, 2010],
    patterns: [],
    evolution: ["2009.png", "2013.png", "2019.png"],
    positioning: true,
  };

  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar />
      <div className="container mt-3">
        <ElementTitle />
        <YearLine present={element.presence} />

        <div className="row mt-4">
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Evolution</div>
            <Timeline serpelement={element} />
          </div>
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Positioning</div>
            <Positioning
              shortname={element.shortname}
              engine={element.engine}
            />
            <div className="sectiontitle mt-4">Design Patterns</div>
            <ElementPatterns />
          </div>
        </div>
      </div>
    </div>
  );
}
