import React, { useState, useEffect } from "react";

import Head from "next/head";
import Bluebar from "../../components/bluebar";
import NavigBar from "../../components/navigbar";
import YearLine from "../../components/yearline";
import ElementBannersSmall from "../../components/elementbannerssmall";

import elements, { bing } from "../../data/elements"; // elements - google elements, bing - bing elements

export function isMember(array, year) {
  var member = false;
  for (let i = 0; i < array.length; i++) {
    if (array[i] == year.toString()) {
      member = true;
      break;
    }
  }
  return member;
}

export async function getStaticProps(context) {
  const year = context.params.year;
  var elements_google = Object.entries(elements).filter((object) => {
    return isMember(object[1].presence, year);
  });
  var elements_bing = Object.entries(bing).filter((object) => {
    return isMember(object[1].presence, year);
  });
  return {
    props: {
      elements_google: elements_google ? elements_google : null,
      elements_bing: elements_bing ? elements_bing : null,
      year,
    }, // will be passed to the page component as props
  };
}

export async function getStaticPaths() {
  let years = [];
  for (let i = 2000; i < 2021; i++) {
    years.push(i);
  }
  const paths = years.map((yr) => {
    return { params: { year: yr.toString() } };
  });
  return {
    paths,
    fallback: false, // return 404 when inexistent
  };
}

export default function YearPage({ elements_google, elements_bing, year }) {
  let years = [];
  for (let i = 2000; i < 2021; i++) {
    years.push(i);
  }

  const prevYear = year == 2000 ? null : parseInt(year) - 1;
  const nextYear = year == 2020 ? null : parseInt(year) + 1;

  function prevYearLink() {
    if (year == 2000) {
      return null;
    } else {
      return (
        <a href={"./" + prevYear}>
          <div>&#8592; {prevYear}</div>
        </a>
      );
    }
  }

  function nextYearLink() {
    if (year == 2020) {
      return null;
    } else {
      return (
        <a href={"./" + nextYear}>
          <div>{nextYear} &#8594;</div>
        </a>
      );
    }
  }

  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar />

      <div className="container mt-3 mb-3">
        <div className="col-12">
          <YearLine present={years} />
          <div className="year-page-title d-flex flex-row justify-content-center align-items-center mt-3">
            {prevYearLink()}
            <div className="actual-year">{year}</div>
            {nextYearLink()}
          </div>
          <div className="row">
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"../assets/google.png"} />
                </div>
              </div>
              <div className="sectiontitle">Elements</div>
              <ElementBannersSmall elements={elements_google} year={year} />
            </div>
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"../assets/bing.png"} />
                </div>
              </div>
              <div className="sectiontitle">Elements</div>
              <ElementBannersSmall elements={elements_bing} year={year} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
