import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bluebar />
      <NavigBar pagename="Articles" />
      <div className="container mt-3 d-flex flex-column about-section">
        <div className="main-title text-center">Articles</div>
        <div>
          <img id="conference-logo" src="./assets/chiirlogo.png" />
          <div className="about-title">ACM SIGIR Conference on Human Information Interaction and Retrieval 2023</div>
          <p>
            We are proud to share with you the two articles derived from this research, presented and published at the CHIIR 2023 Conference in Austin, Texas.
          </p>
          <div className="d-flex justify-content-center paper-row">
            <div className="paper">
              <div className="type">Full Paper</div>
              <a href="https://doi.org/10.1145/3576840.3578320" target="_blank"><img src="./assets/fullpaper.png" /></a>
              <div className="paper-citation">{"Bruno Oliveira and Carla Teixeira Lopes. 2023. The Evolution of Web Search User Interfaces - An Archaeological Analysis of Google Search Engine Result Pages. In Proceedings of the 2023 Conference on Human Information Interaction and Retrieval (CHIIR '23). Association for Computing Machinery, New York, NY, USA, 55–68."}<a href="https://doi.org/10.1145/3576840.3578320" target="_blank"> https://doi.org/10.1145/3576840.3578320</a></div>
            </div>
            <div className="paper">
              <div className="type">Short Paper</div>
              <a href="https://doi.org/10.1145/3576840.3578307" target="_blank"><img src="./assets/shortpaper.png" /></a>
              <div className="paper-citation">{"Bruno Oliveira and Carla Teixeira Lopes. 2023. From 10 Blue Links Pages to Feature-Full Search Engine Results Pages - Analysis of the Temporal Evolution of SERP Features. In Proceedings of the 2023 Conference on Human Information Interaction and Retrieval (CHIIR '23). Association for Computing Machinery, New York, NY, USA, 338–345."}<a href="https://doi.org/10.1145/3576840.3578307" target="_blank"> https://doi.org/10.1145/3576840.3578307</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
