import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";
import ElementBanners from "../components/elementbanners";

import elements, { bing } from "../data/elements"; // elements - google elements, bing - bing elements

export default function Elements() {
  var allelements = elements;
  Object.entries(bing).map((elm) => {
    if (
      Object.entries(elements).find((it_elm) => {
        return it_elm[0] == elm[0];
      })
    ) {
    } else {
      allelements[elm[0]] = elm[1];
    }
  });

  const organic = Object.entries(allelements).filter((elm) => {
    return elm[1].type == "organic";
  });

  const sponsored = Object.entries(allelements).filter((elm) => {
    return elm[1].type == "sponsored";
  });

  const features = Object.entries(allelements).filter((elm) => {
    return elm[1].type == "feature";
  });

  return (
    <div>
      <Head>
        <title>SERP Evolution - Visual Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar pagename="Elements" />
      <div className="container mt-3 mb-3">
        <div className="col-12">
          <div className="sectiontitle">Organic Results</div>
          <ElementBanners elements={organic} />
          <div className="sectiontitle">Sponsored Results</div>
          <ElementBanners elements={sponsored} />
          <div className="sectiontitle">Features</div>
          <ElementBanners elements={features} />
        </div>
      </div>
    </div>
  );
}
