import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";
import ModuleTabs from "../components/moduletabs";
import ElementTitle from "../components/elementtitle";
import YearLine from "../components/yearline";
import Timeline from "../components/timeline";
import Positioning from "../components/positioning";
import ElementPatterns from "../components/elementpatterns";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar />
      <div className="container mt-3">
        <ElementTitle />
        <YearLine />

        <div className="row mt-4">
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Evolution</div>
            <Timeline />
          </div>
          <div className="col-12 col-lg-6">
            <div className="sectiontitle">Positioning</div>
            <Positioning />
            <div className="sectiontitle mt-4">Design Patterns</div>
            <ElementPatterns />
          </div>
        </div>
      </div>
    </div>
  );
}
