import Head from "next/head";

import Bluebar from "../components/bluebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <div className="container"></div>
    </div>
  );
}
