import React, { useState } from "react";

import Head from "next/head";
import Bluebar from "./../components/bluebar";
import NavigBar from "./../components/navigbar";

export default function Layout() {
  const [category, setCategory] = useState("o");
  const categories = [
    ["Organic Results", "#0469b2", "o"],
    ["Sponsored Results", "#c9bd1c", "s"],
    ["Features", "#88c264", "f"],
    ["Navigation & User Inputs", "#e6952d", "n"],
    ["Identity & Search Statistics", "#e10b0b", "i"],
  ];

  var cat_selected = categories.find((cat) => {
    return cat[2] == category;
  });

  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar pagename="Layout" />

      <div className="container mt-3 mb-3">
        <div className="col-12">
          <div className="main-title text-center mb-3">
            Overall Interface Layout
          </div>
          <div className="row">
            <div className="col-12 d-flex justify-content-center align-items-center flex-wrap">
              {categories.map((cat, key) => {
                return (
                  <div
                    className={
                      "category-badge " + (category == cat[2] ? "selected" : "")
                    }
                    style={{ backgroundColor: cat[1] }}
                    onClick={() => setCategory(cat[2])}
                    key={key}
                  >
                    {cat[0]}
                  </div>
                );
              })}
            </div>
          </div>
          <div className="row">
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"./assets/google.png"} />
                </div>
              </div>
              <div className="sectiontitle">Layout for {cat_selected[0]}</div>
              <div className="d-flex justify-content-center flex-wrap">
                <div>
                  {category == "n" || category == "i" ? null : (
                    <img
                      className="positioning model"
                      src="./assets/test_serptop.png"
                    />
                  )}
                  <img
                    className="positioning result layout-result"
                    src={"./assets/layout/g_" + category + ".png"}
                  />
                </div>
                {category == "o" || category == "s" || category == "f" ? (
                  <div className="layout-gif">
                    <img src={"./assets/layout/g_" + category + ".gif"} />
                  </div>
                ) : null}
              </div>
            </div>
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"./assets/bing.png"} />
                </div>
              </div>
              <div className="sectiontitle">Layout for {cat_selected[0]}</div>
              <div className="d-flex justify-content-center flex-wrap">
                <div>
                  {category == "n" || category == "i" ? null : (
                    <img
                      className="positioning model"
                      src="./assets/test_serptop.png"
                    />
                  )}
                  <img
                    className="positioning result layout-result"
                    src={"./assets/layout/b_" + category + ".png"}
                  />
                </div>
                {category == "o" || category == "s" || category == "f" ? (
                  <div className="layout-gif">
                    <img src={"./assets/layout/b_" + category + ".gif"} />
                  </div>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
