import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <div className="container mt-3 d-flex flex-column text-center">
        <h3>Most Searched Queries</h3>
        Available soon.
      </div>
    </div>
  );
}
