import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar pagename="Timeline" />
      <div className="container mt-3 d-flex flex-column text-center">
        This timeline will sum up all the major changes occured in both SERP,
        regarding element introduction and main navigation items launched.
        <hr />
        Available from 11/12th July.
      </div>
    </div>
  );
}
