import Head from "next/head";
import Bluebar from "../components/bluebar";
import NavigBar from "../components/navigbar";
import { Accordion, Card } from "react-bootstrap";

export default function VisualEvolution() {
  return (
    <div>
      <Head>
        <title>SERP Evolution - Visual Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar />
      <div className="container mt-3 mb-3">
        <div className="row mt-4">
          <div className="col-12 col-lg-6">
            <div className="d-flex flex-column align-items-center">
              <div className="element-engine">
                <img src={"./assets/google.png"} />
              </div>
            </div>
            <Accordion>
              <Card>
                <Accordion.Toggle as={Card.Header} eventKey="0">
                  Identity and Search Statistics
                </Accordion.Toggle>

                <Accordion.Collapse eventKey="0">
                  <Card.Body>This is first tab body</Card.Body>
                </Accordion.Collapse>
              </Card>

              <Card>
                <Accordion.Toggle as={Card.Header} eventKey="1">
                  TAB 2
                </Accordion.Toggle>

                <Accordion.Collapse eventKey="1">
                  <Card.Body>This is second tab body</Card.Body>
                </Accordion.Collapse>
              </Card>
            </Accordion>
          </div>
          <div className="col-12 col-lg-6">
            <div className="d-flex flex-column align-items-center">
              <div className="element-engine">
                <img src={"./assets/bing.png"} />
              </div>
            </div>
            <div className="sectiontitle">Positioning</div>
          </div>
        </div>
      </div>
    </div>
  );
}
