import React, { useState, useEffect } from "react";

import Head from "next/head";
import Bluebar from "../../components/bluebar";
import NavigBar from "../../components/navigbar";
import ElementBannersSmall from "../../components/elementbannerssmall";

import elements, { bing } from "../../data/elements"; // elements - google elements, bing - bing elements
import patterns from "../../data/patterns";

export function isMember(array, pattern) {
  var member = false;
  for (let i = 0; i < pattern.length + 1; i++) {
    if (array[i] == pattern) {
      member = true;
      break;
    }
  }
  return member;
}

export async function getStaticProps(context) {
  const pattern = context.params.pattern;
  var elements_google = Object.entries(elements).filter((object) => {
    return isMember(object[1].patterns, pattern);
  });
  var elements_bing = Object.entries(bing).filter((object) => {
    return isMember(object[1].patterns, pattern);
  });
  var pattern_obj = Object.entries(patterns).find((pat) => {
    return pat[0] == pattern;
  });

  return {
    props: {
      elements_google: elements_google ? elements_google : null,
      elements_bing: elements_bing ? elements_bing : null,
      pattern_obj,
    }, // will be passed to the page component as props
  };
}

export async function getStaticPaths() {
  const paths = Object.entries(patterns).map((pat) => {
    return { params: { pattern: pat[0] } };
  });
  return {
    paths,
    fallback: false, // return 404 when inexistent
  };
}

export default function PatternPage({
  elements_google,
  elements_bing,
  pattern_obj,
}) {
  return (
    <div>
      <Head>
        <title>SERP Evolution</title>
        <meta
          name="A study on the evolution of user interfaces"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bluebar />
      <NavigBar pagename="Patterns" />

      <div className="container mt-3 mb-3">
        <div className="col-12">
          <div className="row">
            <div className="col-12 d-flex flex-column justify-content-center align-items-center">
              <div className="main-title">Design Patterns</div>
              <div className="pattern-title">{pattern_obj[1].name}</div>
              <div className="pattern-description">
                {pattern_obj[1].description}
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"../assets/google.png"} />
                </div>
              </div>
              <div className="sectiontitle">Elements</div>
              <ElementBannersSmall elements={elements_google} />
            </div>
            <div className="col-12 col-lg-6">
              <div className="d-flex flex-column align-items-center">
                <div className="element-engine year">
                  <img src={"../assets/bing.png"} />
                </div>
              </div>
              <div className="sectiontitle">Elements</div>
              <ElementBannersSmall elements={elements_bing} />
            </div>
          </div>
          <div className="row">
            <div className="col-12 gallery">
              <div className="sectiontitle">Gallery</div>
              <div className="pattern-gallery">
                {pattern_obj[1].images.map((img, key) => {
                  var url =
                    "../assets/patterns/" +
                    pattern_obj[1].shortname +
                    "/" +
                    img;
                  return <img key={key} src={url} />;
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
